//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Bicis_Scooters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_VENTAS_BICICLETA_SCOOTEREntities : DbContext
    {
        public BD_VENTAS_BICICLETA_SCOOTEREntities()
            : base("name=BD_VENTAS_BICICLETA_SCOOTEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_Cliente_Actualizar(Nullable<int> cod_cliente, string nom_cliente, string ape_cliente, string dni_cliente, string correo_cliente, string cel_cliente, Nullable<int> cod_direccion, string username_cliente, string paswoord_cliente)
        {
            var cod_clienteParameter = cod_cliente.HasValue ?
                new ObjectParameter("cod_cliente", cod_cliente) :
                new ObjectParameter("cod_cliente", typeof(int));
    
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var ape_clienteParameter = ape_cliente != null ?
                new ObjectParameter("ape_cliente", ape_cliente) :
                new ObjectParameter("ape_cliente", typeof(string));
    
            var dni_clienteParameter = dni_cliente != null ?
                new ObjectParameter("dni_cliente", dni_cliente) :
                new ObjectParameter("dni_cliente", typeof(string));
    
            var correo_clienteParameter = correo_cliente != null ?
                new ObjectParameter("correo_cliente", correo_cliente) :
                new ObjectParameter("correo_cliente", typeof(string));
    
            var cel_clienteParameter = cel_cliente != null ?
                new ObjectParameter("cel_cliente", cel_cliente) :
                new ObjectParameter("cel_cliente", typeof(string));
    
            var cod_direccionParameter = cod_direccion.HasValue ?
                new ObjectParameter("cod_direccion", cod_direccion) :
                new ObjectParameter("cod_direccion", typeof(int));
    
            var username_clienteParameter = username_cliente != null ?
                new ObjectParameter("username_cliente", username_cliente) :
                new ObjectParameter("username_cliente", typeof(string));
    
            var paswoord_clienteParameter = paswoord_cliente != null ?
                new ObjectParameter("paswoord_cliente", paswoord_cliente) :
                new ObjectParameter("paswoord_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Cliente_Actualizar", cod_clienteParameter, nom_clienteParameter, ape_clienteParameter, dni_clienteParameter, correo_clienteParameter, cel_clienteParameter, cod_direccionParameter, username_clienteParameter, paswoord_clienteParameter);
        }
    
        public virtual ObjectResult<usp_Cliente_Buscar_Result> usp_Cliente_Buscar(string username_cliente, string paswoord_cliente, string nom_cliente, string ape_cliente)
        {
            var username_clienteParameter = username_cliente != null ?
                new ObjectParameter("username_cliente", username_cliente) :
                new ObjectParameter("username_cliente", typeof(string));
    
            var paswoord_clienteParameter = paswoord_cliente != null ?
                new ObjectParameter("paswoord_cliente", paswoord_cliente) :
                new ObjectParameter("paswoord_cliente", typeof(string));
    
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var ape_clienteParameter = ape_cliente != null ?
                new ObjectParameter("ape_cliente", ape_cliente) :
                new ObjectParameter("ape_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Cliente_Buscar_Result>("usp_Cliente_Buscar", username_clienteParameter, paswoord_clienteParameter, nom_clienteParameter, ape_clienteParameter);
        }
    
        public virtual int usp_Cliente_Insertar(string nom_cliente, string ape_cliente, string dni_cliente, string correo_cliente, string cel_cliente, Nullable<int> cod_direccion, string username_cliente, string paswoord_cliente)
        {
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var ape_clienteParameter = ape_cliente != null ?
                new ObjectParameter("ape_cliente", ape_cliente) :
                new ObjectParameter("ape_cliente", typeof(string));
    
            var dni_clienteParameter = dni_cliente != null ?
                new ObjectParameter("dni_cliente", dni_cliente) :
                new ObjectParameter("dni_cliente", typeof(string));
    
            var correo_clienteParameter = correo_cliente != null ?
                new ObjectParameter("correo_cliente", correo_cliente) :
                new ObjectParameter("correo_cliente", typeof(string));
    
            var cel_clienteParameter = cel_cliente != null ?
                new ObjectParameter("cel_cliente", cel_cliente) :
                new ObjectParameter("cel_cliente", typeof(string));
    
            var cod_direccionParameter = cod_direccion.HasValue ?
                new ObjectParameter("cod_direccion", cod_direccion) :
                new ObjectParameter("cod_direccion", typeof(int));
    
            var username_clienteParameter = username_cliente != null ?
                new ObjectParameter("username_cliente", username_cliente) :
                new ObjectParameter("username_cliente", typeof(string));
    
            var paswoord_clienteParameter = paswoord_cliente != null ?
                new ObjectParameter("paswoord_cliente", paswoord_cliente) :
                new ObjectParameter("paswoord_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Cliente_Insertar", nom_clienteParameter, ape_clienteParameter, dni_clienteParameter, correo_clienteParameter, cel_clienteParameter, cod_direccionParameter, username_clienteParameter, paswoord_clienteParameter);
        }
    }
}
